
import __ASTRO_IMAGE_IMPORT_Z2d8IRG from "./assets/fmm-1-level.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_Z1HPtPA from "./assets/fmm-2-level.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_zOfIl from "./assets/lower-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_2QEj5 from "assets/Laplacian_1D_train_loss.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_Z14Dv4r from "./assets/laplacian_1D.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_1UaAg3 from "assets/lu-approx.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
import __ASTRO_IMAGE_IMPORT_Z1FDFp4 from "./assets/LU-approx.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md";
export default new Map([["./assets/fmm-1-level.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_Z2d8IRG], ["./assets/fmm-2-level.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_Z1HPtPA], ["./assets/lower-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_zOfIl], ["assets/Laplacian_1D_train_loss.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_2QEj5], ["./assets/laplacian_1D.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_Z14Dv4r], ["assets/lu-approx.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_1UaAg3], ["./assets/LU-approx.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearn_LU.md", __ASTRO_IMAGE_IMPORT_Z1FDFp4]]);
		